version: '3.7'

services:

  elasticsearch:
    image: elasticsearch:7.16.2
    volumes:
      - ./server/es/data:/usr/share/elasticsearch/data
      - ./plugins:/usr/share/elasticsearch/test
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xmx256m -Xms256m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"

  kibana:
    image: kibana:7.16.2
    environment:
      - ELASTICSEARCH_URL=elasticsearch://elasticsearch:9200
    ports:
      - "5601:5601"
